#!/bin/bash

source ./read-env.sh

EXPRESS_HELPER_SERVER_TARGET_PATH_BUILD_DIR=$(read_env EXPRESS_HELPER_SERVER_TARGET_PATH_BUILD_DIR .env.prod."$1")

echo $EXPRESS_HELPER_SERVER_TARGET_PATH_BUILD_DIR
