swagger: '2.0'
# See also: https://swagger.io/specification/v2/
info:
  title: QR test API
  description: 'Demo *(Возможно, потребуется включить **CORS**)*'
  version: '1.0.0'
  contact:
    email: 'selection4test@gmail.com'
host: pravosleva.ru
basePath: /express-helper/qr/
schemes:
  - http
tags:
  - name: 'generate_sample'
    description: 'Generate QR code by payload'
    externalDocs:
      description: 'Сгенерить QR по строке (аргументу, как правило, это ссылка)'
      url: 'swagger.io'
paths:
  /generate-sample:
    get:
      tags:
        - 'generate_sample'
      produces:
        - application/json
      parameters:
        - in: query
          name: body
          required: true
          schema:
            $ref: '#/definitions/GenerateSampleParams'
      summary: 'Returns QR as data-image'
      description: 'Вернет QR'
      responses:
        200:
          description: 'OK'
          schema:
            info: 'Success response sample'
            type: object
            properties:
              ok:
                type: boolean
                required: true
              qr:
                type: string
                required: true
definitions:
  GenerateSampleParams:
    type: object
    properties:
      payload:
        required: true
        type: string
        description: 'Your payload in QR'
